### ISSUE TITLE
Prepare and print paper wallets for ethBerlin

### ISSUE THREAD

**Issue by art1c0** [leapdao/paper-wallet#4]
# Bounty

## Scope
Paper wallets for Planet A were printed only for the needs of Social Distortion Protocol.
Therefore it's URGENTLY required to prepare and print them in one day before ethBerlin starts.
Design has to be updated to print one side of the page and make it foldable like a passport.

## Deliverables
Paper wallets printed beautifully and on time.

## Gain for the project
Proper participation in ethBerlin with Planet A game.

### Publicly visible delivery
Printed paper wallets.

## Roles
bounty gardener: @articobandurini / 10%
bounty worker: @articobandurini / 75%
bounty reviewer: @johannbarbie / 15%

**Comment by johba37** [comment]
closed, should be taken care of in SDP repo
